// <auto-generated />
using Gestion_brasserie2021_CHIARELLI_THOMAS.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gestion_brasserie2021_CHIARELLI_THOMAS.Migrations
{
    [DbContext(typeof(DataContext.DataContext))]
    [Migration("20210805142254_Beerwholesaler_entity")]
    partial class Beerwholesaler_entity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gestion_brasserie2021_CHIARELLI_THOMAS.Models.Beer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Alchool")
                        .HasColumnType("float");

                    b.Property<int>("IdBrewer")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdBrewer");

                    b.ToTable("Beers");
                });

            modelBuilder.Entity("Gestion_brasserie2021_CHIARELLI_THOMAS.Models.BeerWholesaler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeerQuantity")
                        .HasColumnType("int");

                    b.Property<int>("IdBeer")
                        .HasColumnType("int");

                    b.Property<int>("IdWholesaler")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdBeer");

                    b.HasIndex("IdWholesaler");

                    b.ToTable("BeerWholesalers");
                });

            modelBuilder.Entity("Gestion_brasserie2021_CHIARELLI_THOMAS.Models.Brewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Breweries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Test"
                        });
                });

            modelBuilder.Entity("Gestion_brasserie2021_CHIARELLI_THOMAS.Models.Wholesaler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wholesalers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TestGrossiste"
                        });
                });

            modelBuilder.Entity("Gestion_brasserie2021_CHIARELLI_THOMAS.Models.Beer", b =>
                {
                    b.HasOne("Gestion_brasserie2021_CHIARELLI_THOMAS.Models.Brewer", "Brewer")
                        .WithMany()
                        .HasForeignKey("IdBrewer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brewer");
                });

            modelBuilder.Entity("Gestion_brasserie2021_CHIARELLI_THOMAS.Models.BeerWholesaler", b =>
                {
                    b.HasOne("Gestion_brasserie2021_CHIARELLI_THOMAS.Models.Brewer", "Brewer")
                        .WithMany()
                        .HasForeignKey("IdBeer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_brasserie2021_CHIARELLI_THOMAS.Models.Wholesaler", "Wholesaler")
                        .WithMany()
                        .HasForeignKey("IdWholesaler")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brewer");

                    b.Navigation("Wholesaler");
                });
#pragma warning restore 612, 618
        }
    }
}
